public enum SSObjectID {
	SHIP_MISSILE = 0,
	ENEMY_SHIP_1 = 1,
	ENEMY_SHIP_2 = 2,
	ENEMY_SHIP_3 = 3,
	ENEMY_SHIP_4 = 4,
	ENEMY_SHIP_5 = 5,
	ENEMY_SHIP_6 = 6,
	ENEMY_SHIP_7 = 7,
	ENEMY_SHIP_8 = 8,
	EXPLOSION_MISSILE = 9,
	EXPLOSION_ENEMY = 10,
	EXPLOSION_SHIP = 11
};